---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx latest version
      apt:
        name: nginx
        state: latest

    - name: Run Nginx
      systemd:
        name: nginx
        state: started